version: "3.8"

services:
  nikestore:
    build:
      context: .
    container_name: create-next-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - my-nike


  mongodb:
    image: mongo:latest
    container_name: my_mongo
    ports:
      - "27017:27017"
    networks:
      - my-nike
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - my-nike

volumes:
     mongo-data:  
networks:
     my-nike:

  
