kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nikeapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hyysuresh/nikestore.git
    targetRevision: master
    path: nikestore/k8s
  destination:
    server:  https://172.31.20.0:33893
    namespace: default 
  syncpolicy:
    automated:
      prune: true
      selfHeal: true
  