kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: nikeapp
  namespace: argocd
spec:
  project: my-app
  source:
    repoURL: https://github.com/Hyysuresh/nikestore.git
    targetRevision: master
    path: k8s/
  destination:
    server:  https://172.31.20.0:33893
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  
